// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using firstASP.Data;

#nullable disable

namespace firstASP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001022351_AddCustomer")]
    partial class AddCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("firstASP.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Rizal St",
                            City = "Manila",
                            ContactName = "Ana Cruz",
                            CustomerName = "Acme Corp",
                            Email = "ana@acme.com",
                            Phone = "0917-111-1001",
                            State = "NCR",
                            ZipCode = "1000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "34 Mabini Ave",
                            City = "Cebu",
                            ContactName = "Ben Lim",
                            CustomerName = "BlueTech",
                            Email = "ben@bluetech.com",
                            Phone = "0917-111-1002",
                            State = "Cebu",
                            ZipCode = "6000"
                        },
                        new
                        {
                            Id = 3,
                            Address = "56 Bonifacio",
                            City = "Davao",
                            ContactName = "Cara Reyes",
                            CustomerName = "GreenMart",
                            Email = "cara@green.com",
                            Phone = "0917-111-1003",
                            State = "Davao",
                            ZipCode = "8000"
                        },
                        new
                        {
                            Id = 4,
                            Address = "78 Luna St",
                            City = "Manila",
                            ContactName = "Dan Tan",
                            CustomerName = "SunFoods",
                            Email = "dan@sunfoods.com",
                            Phone = "0917-111-1004",
                            State = "NCR",
                            ZipCode = "1001"
                        },
                        new
                        {
                            Id = 5,
                            Address = "9 Osmena Blvd",
                            City = "Cebu",
                            ContactName = "Ella Santos",
                            CustomerName = "PrimeParts",
                            Email = "ella@prime.com",
                            Phone = "0917-111-1005",
                            State = "Cebu",
                            ZipCode = "6001"
                        },
                        new
                        {
                            Id = 6,
                            Address = "21 Quezon Ave",
                            City = "Davao",
                            ContactName = "Faye Ong",
                            CustomerName = "CityCare",
                            Email = "faye@citycare.com",
                            Phone = "0917-111-1006",
                            State = "Davao",
                            ZipCode = "8001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "3 Roxas St",
                            City = "Manila",
                            ContactName = "Gio Ramos",
                            CustomerName = "NovaSupply",
                            Email = "gio@nova.com",
                            Phone = "0917-111-1007",
                            State = "NCR",
                            ZipCode = "1002"
                        },
                        new
                        {
                            Id = 8,
                            Address = "45 Aguinaldo",
                            City = "Cebu",
                            ContactName = "Hana Cruz",
                            CustomerName = "StarLink",
                            Email = "hana@starlink.com",
                            Phone = "0917-111-1008",
                            State = "Cebu",
                            ZipCode = "6002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
